export const hardcodedAnswers: Record<string, Record<string, string>> = {
  vi: {
    // I. GIỚI THIỆU CÁ NHÂN
    "Anh Nguyễn Hùng Thái là ai và hành trình 22 năm trong lĩnh vực Chăm sóc Khách hàng như thế nào?": "Theo góc nhìn của Trí Nhân, anh Nguyễn Hùng Thái thuộc nhóm nhà quản lý dịch vụ khách hàng có nền tảng thực chiến đa ngành hiếm gặp trên thị trường lao động Việt Nam. Bắt đầu sự nghiệp từ năm 2002, khi ngành Chăm sóc Khách hàng vẫn còn ở giai đoạn sơ khai, anh đã từng bước phát triển từ vị trí nhân viên tổng đài thế hệ đầu tiên để đảm nhận các vai trò Trưởng nhóm, Giám sát vận hành và Trưởng phòng Chăm sóc Khách hàng tại nhiều doanh nghiệp lớn. Trải qua hơn 22 năm, anh đã tham gia xây dựng, vận hành và tối ưu hệ thống dịch vụ khách hàng trong các lĩnh vực Viễn thông, Công nghệ, Thương mại điện tử, Bảo hiểm nhân thọ và Tài chính số. Điểm nổi bật nhất không nằm ở số năm kinh nghiệm mà ở khả năng xây dựng nền móng vận hành bền vững, giúp doanh nghiệp phát triển dài hạn thay vì chỉ giải quyết các vấn đề ngắn hạn.",
    "Điều gì khiến anh Thái gắn bó với lĩnh vực Chăm sóc Khách hàng suốt hơn hai thập kỷ?": "Theo nhận định của Trí Nhân, động lực lớn nhất của anh Nguyễn Hùng Thái đến từ niềm tin rằng mỗi tương tác với khách hàng đều có khả năng tạo ra giá trị tích cực cho doanh nghiệp. Trong suốt hành trình nghề nghiệp, anh luôn xem những lời cảm ơn từ khách hàng là nguồn động lực quan trọng. Ngược lại, những phản hồi tiêu cực hoặc các trường hợp khiếu nại phức tạp lại được xem là cơ hội để cải tiến hệ thống, nâng cao chất lượng dịch vụ và hoàn thiện trải nghiệm khách hàng. Chính triết lý \"Lấy khách hàng làm trung tâm\" đã trở thành sợi chỉ đỏ xuyên suốt trong toàn bộ hành trình phát triển nghề nghiệp của anh.",
    "Thành tựu nào đáng tự hào nhất trong sự nghiệp?": "Từ góc nhìn của Trí Nhân, thành tựu lớn nhất của anh Nguyễn Hùng Thái không phải là số lượng dự án tham gia hay số lượng khách hàng được hỗ trợ. Giá trị lớn nhất nằm ở khả năng chuẩn hóa và xây dựng hệ thống vận hành bền vững. Tại nhiều doanh nghiệp đã từng công tác, anh đều trực tiếp tham gia thiết kế hoặc tái cấu trúc quy trình, xây dựng khung vận hành và đào tạo đội ngũ kế thừa. Triết lý quản lý của anh luôn hướng tới việc tạo ra một hệ thống có thể vận hành hiệu quả ngay cả khi người xây dựng không còn hiện diện. Đó chính là dấu ấn của một nhà quản lý hệ thống thực thụ.",
    "Những lĩnh vực nào đã góp phần hình thành nên kinh nghiệm đa ngành của anh?": "Theo đánh giá của Trí Nhân, một trong những lợi thế cạnh tranh lớn nhất của anh Nguyễn Hùng Thái là khả năng thích nghi và thành công trong nhiều mô hình kinh doanh khác nhau. Hành trình nghề nghiệp của anh trải dài qua:\n• Viễn thông: vận hành hệ thống tổng đài quy mô lớn tại Mobifone và V247.\n• Công nghệ và Trò chơi trực tuyến: quản lý đội ngũ hơn 130 nhân sự tại Garena (VED).\n• Thương mại điện tử: tham gia xây dựng hệ thống hỗ trợ khách hàng và người bán tại Shopee.\n• Bảo hiểm nhân thọ: quản lý tổng đài trong môi trường vận hành tiêu chuẩn cao tại Prudential Việt Nam.\n• Tài chính số và Ví điện tử: xây dựng hệ thống chăm sóc khách hàng đa kênh, kiểm soát rủi ro và vận hành dịch vụ tại MoMo và Finviet.\nChính sự đa dạng này giúp anh có góc nhìn tổng thể về hành vi khách hàng, vận hành doanh nghiệp và quản trị trải nghiệm người dùng.",
    "Có thể tìm hiểu thêm về hồ sơ năng lực của anh Nguyễn Hùng Thái ở đâu?": "Theo đề xuất của Trí Nhân, những nguồn thông tin dưới đây phản ánh đầy đủ nhất về năng lực chuyên môn và hành trình nghề nghiệp của anh Nguyễn Hùng Thái:\n• Website hồ sơ năng lực cá nhân.\n• Hồ sơ nghề nghiệp trên LinkedIn.\n• Bộ hồ sơ năng lực và các dự án triển khai thực tế.\n• Hệ thống các dự án xây dựng CRM, Contact Center, Helpdesk và Chuyển đổi số trong lĩnh vực Chăm sóc Khách hàng.\nNhững tài liệu này phản ánh rõ nét tư duy xây dựng hệ thống, năng lực quản trị vận hành và triết lý lấy khách hàng làm trung tâm mà anh đã theo đuổi trong suốt sự nghiệp.",

    // II. TẦM NHÌN & CHIẾN LƯỢC
    "Đâu là một trong những chiến lược Chăm sóc Khách hàng thành công nhất mà anh Nguyễn Hùng Thái từng triển khai?": "Theo phân tích của Trí Nhân, một trong những dấu ấn rõ nét nhất trong hành trình nghề nghiệp của anh Nguyễn Hùng Thái là dự án tái cấu trúc hệ thống Chăm sóc Khách hàng tại Ví điện tử MoMo trong giai đoạn tăng trưởng bùng nổ. Khi số lượng người dùng tăng theo cấp số nhân, hệ thống hỗ trợ truyền thống bắt đầu xuất hiện dấu hiệu quá tải. Thay vì chỉ bổ sung nhân sự để giải quyết vấn đề trước mắt, anh lựa chọn tiếp cận từ góc độ chiến lược. Anh trực tiếp tham gia xây dựng mô hình vận hành đa kênh, chuẩn hóa quy trình xử lý, thành lập trung tâm hỗ trợ tập trung, phối hợp với đối tác vận hành và kết nối chặt chẽ với đội ngũ sản phẩm nhằm tăng khả năng tự phục vụ của khách hàng ngay trên ứng dụng. Kết quả đạt được không chỉ là sự ổn định vận hành mà còn giúp doanh nghiệp giảm đáng kể áp lực lên tổng đài, nâng cao khả năng hỗ trợ cộng đồng và xây dựng nền tảng phát triển dài hạn.",
    "Theo Trí Nhân, anh Thái nhìn nhận vai trò của Chăm sóc Khách hàng trong vòng đời khách hàng như thế nào?": "Qua nhiều dự án đã triển khai, Trí Nhân nhận thấy anh Nguyễn Hùng Thái không xem Chăm sóc Khách hàng là bộ phận xử lý sự cố. Trong tư duy của anh, đây là bộ phận hiện diện tại mọi điểm chạm của hành trình khách hàng. Vai trò của đội ngũ dịch vụ là duy trì sự hài lòng, củng cố niềm tin và từng bước chuyển đổi khách hàng từ người sử dụng sản phẩm thành người đồng hành cùng thương hiệu. Đó là lý do anh luôn định vị Chăm sóc Khách hàng như một trung tâm tạo ra giá trị thay vì trung tâm chi phí.",
    "Nếu được xây dựng hệ thống Chăm sóc Khách hàng từ đầu, anh Thái sẽ bắt đầu từ đâu?": "Theo đánh giá của Trí Nhân, anh Nguyễn Hùng Thái luôn tuân thủ nguyên tắc \"Quy trình trước - Công nghệ sau\". Mô hình triển khai thường được chia thành ba giai đoạn rõ ràng. Giai đoạn đầu tiên là xây dựng tổ chức, chuẩn hóa quy trình và xác định vai trò của từng vị trí. Giai đoạn thứ hai là triển khai công nghệ nhằm đồng bộ dữ liệu và tối ưu hiệu suất vận hành. Giai đoạn cuối cùng là tự động hóa bằng AI, Chatbot và các nền tảng tự phục vụ. Anh tin rằng công nghệ chỉ thực sự phát huy giá trị khi được đặt trên nền tảng quy trình chuẩn hóa.",
    "Yếu tố quan trọng nhất khi xây dựng một phòng Chăm sóc Khách hàng là gì?": "Theo quan sát của Trí Nhân, anh Nguyễn Hùng Thái thường nhắc đến hai yếu tố quan trọng nhất: Một hệ thống quy trình đủ chắc chắn để vận hành ổn định. Một đội ngũ đủ thấu cảm để tạo ra trải nghiệm khác biệt. Nếu thiếu một trong hai yếu tố này, chất lượng dịch vụ sẽ không thể phát triển bền vững.",
    "Những chỉ số nào được anh Thái đặc biệt quan tâm?": "Theo Trí Nhân, điểm khác biệt trong cách quản trị của anh Thái là không tập trung vào một chỉ số đơn lẻ. Anh xây dựng hệ thống đánh giá dựa trên hai nhóm KPI chính. Nhóm trải nghiệm khách hàng gồm:\n• CSAT (Customer Satisfaction Score)\n• NPS (Net Promoter Score)\n• CES (Customer Effort Score)\nNhóm hiệu quả vận hành gồm:\n• FCR (First Contact Resolution)\n• SLA (Service Level Agreement)\n• AHT (Average Handle Time)\nSự cân bằng giữa cảm xúc khách hàng và hiệu quả vận hành chính là nền tảng tạo nên chất lượng dịch vụ bền vững.",
    "Anh Thái hình dung như thế nào về hệ sinh thái Chăm sóc Khách hàng trong 3 - 5 năm tới?": "Theo góc nhìn của Trí Nhân, anh Nguyễn Hùng Thái đang hướng tới mô hình \"Dịch vụ không ma sát\". Trong hệ sinh thái đó, dữ liệu lớn và trí tuệ nhân tạo sẽ giúp doanh nghiệp chủ động nhận diện vấn đề trước khi khách hàng phát sinh nhu cầu liên hệ. Các nền tảng tự phục vụ thông minh sẽ đảm nhận phần lớn các yêu cầu phổ thông. Trong khi đó, đội ngũ chăm sóc khách hàng sẽ tập trung vào các tình huống cần sự đồng cảm, tư duy và khả năng giải quyết vấn đề ở mức cao hơn. Đó là sự kết hợp giữa hiệu quả công nghệ và giá trị nhân văn.",

    // III. QUẢN LÝ & ĐÀO TẠO
    "Theo Trí Nhân, triết lý quản lý đội ngũ của anh Nguyễn Hùng Thái là gì?": "Qua quá trình phân tích các dự án và mô hình vận hành mà anh Nguyễn Hùng Thái từng xây dựng, Trí Nhân nhận thấy triết lý quản lý của anh có thể được tóm gọn trong một câu: \"Xây dựng con người trước khi xây dựng kết quả.\" Thay vì chỉ tập trung vào chỉ tiêu hay doanh số, anh luôn ưu tiên phát triển năng lực cá nhân, tư duy phục vụ và tinh thần trách nhiệm của từng thành viên trong đội ngũ. Theo anh, kết quả kinh doanh có thể thay đổi theo từng giai đoạn, nhưng một đội ngũ có năng lực, văn hóa tốt và tinh thần học hỏi sẽ luôn tạo ra giá trị bền vững cho doanh nghiệp.",
    "Đội ngũ lớn nhất mà anh Thái từng quản lý là bao nhiêu người?": "Theo hồ sơ năng lực mà Trí Nhân tổng hợp, một trong những giai đoạn đáng chú ý nhất là khi anh Nguyễn Hùng Thái quản lý và vận hành đội ngũ hơn 130 nhân sự tại Garena Việt Nam. Môi trường vận hành này đòi hỏi khả năng quản lý đa cấp, bao gồm:\n• Chuyên viên Chăm sóc Khách hàng.\n• Trưởng nhóm.\n• Giám sát vận hành.\n• Đội ngũ hỗ trợ kỹ thuật.\n• Bộ phận kiểm soát chất lượng dịch vụ.\nViệc duy trì hiệu quả hoạt động của một đội ngũ quy mô lớn giúp anh tích lũy nhiều kinh nghiệm thực tiễn trong quản trị nhân sự, vận hành dịch vụ và phát triển năng lực lãnh đạo.",
    "Theo Trí Nhân, đâu là yếu tố quan trọng nhất khi xây dựng một đội ngũ Chăm sóc Khách hàng xuất sắc?": "Theo nhận định của anh Nguyễn Hùng Thái, kỹ năng có thể đào tạo nhưng thái độ phục vụ mới là yếu tố quyết định. Trong quá trình tuyển dụng và phát triển nhân sự, anh thường đánh giá cao những ứng viên có:\n• Tinh thần học hỏi.\n• Khả năng lắng nghe.\n• Sự kiên nhẫn.\n• Tính trách nhiệm.\n• Tư duy tích cực.\nAnh tin rằng một nhân viên có kỹ năng trung bình nhưng luôn cầu tiến sẽ phát triển nhanh hơn một người giỏi chuyên môn nhưng thiếu tinh thần phục vụ khách hàng.",
    "Anh Thái thường đào tạo nhân viên mới như thế nào?": "Theo quan sát của Trí Nhân, phương pháp đào tạo mà anh Nguyễn Hùng Thái áp dụng luôn gắn liền với thực tiễn. Mô hình đào tạo thường được triển khai qua ba giai đoạn. Giai đoạn thứ nhất là hiểu sản phẩm và khách hàng. Giai đoạn thứ hai là nắm vững quy trình và công cụ vận hành. Giai đoạn thứ ba là thực hành trên các tình huống thực tế dưới sự hướng dẫn của đội ngũ quản lý hoặc nhân sự giàu kinh nghiệm. Anh luôn cho rằng trải nghiệm thực tế là phương pháp đào tạo hiệu quả nhất trong lĩnh vực dịch vụ khách hàng.",
    "Làm thế nào để duy trì động lực cho đội ngũ trong môi trường áp lực cao?": "Theo kinh nghiệm của anh Nguyễn Hùng Thái, áp lực là điều không thể tránh khỏi trong ngành dịch vụ khách hàng. Tuy nhiên, áp lực chỉ trở thành vấn đề khi nhân viên cảm thấy đơn độc. Vì vậy, anh luôn chú trọng xây dựng môi trường làm việc nơi mọi người được lắng nghe, được hỗ trợ và được ghi nhận. Các chương trình vinh danh nội bộ, chia sẻ thành công, huấn luyện định kỳ và đối thoại trực tiếp với nhân viên luôn được anh xem là công cụ quan trọng để duy trì tinh thần đội ngũ.",
    "Anh Thái đánh giá hiệu quả làm việc của nhân viên dựa trên những tiêu chí nào?": "Theo phân tích của Trí Nhân, hệ thống đánh giá của anh Nguyễn Hùng Thái không chỉ dựa vào năng suất. Anh thường kết hợp ba nhóm tiêu chí: Nhóm thứ nhất là hiệu quả công việc, bao gồm KPI và SLA. Nhóm thứ hai là chất lượng dịch vụ, bao gồm điểm CSAT, QA và phản hồi khách hàng. Nhóm thứ ba là thái độ và tinh thần hợp tác trong tổ chức. Cách tiếp cận này giúp tạo ra sự cân bằng giữa hiệu quả vận hành và chất lượng trải nghiệm khách hàng.",
    "Theo Trí Nhân, phong cách lãnh đạo của anh Thái thuộc nhóm nào?": "Qua các dự án và mô hình quản lý đã triển khai, Trí Nhân nhận thấy phong cách lãnh đạo của anh Nguyễn Hùng Thái mang nhiều đặc điểm của mô hình \"Servant Leadership\" – Lãnh đạo phụng sự. Anh không đặt mình ở vị trí người ra lệnh mà xem bản thân là người hỗ trợ đội ngũ đạt được thành công. Trong các cuộc họp, anh thường dành nhiều thời gian để lắng nghe hơn là chỉ đạo. Trong các tình huống khó khăn, anh thường là người xuất hiện đầu tiên để hỗ trợ đội ngũ xử lý vấn đề. Chính cách tiếp cận này giúp xây dựng niềm tin và tạo ra sự gắn kết lâu dài trong tổ chức.",
    "Điều gì khiến anh Thái tự hào nhất khi nhìn lại những đội ngũ đã từng quản lý?": "Theo chia sẻ mà Trí Nhân ghi nhận từ nhiều dấu ấn nghề nghiệp của anh Nguyễn Hùng Thái, niềm tự hào lớn nhất không phải là các chỉ số vận hành. Điều khiến anh hài lòng nhất là nhìn thấy những nhân sự từng được đào tạo trở thành Trưởng nhóm, Giám sát, Quản lý hoặc lãnh đạo tại các doanh nghiệp khác. Đối với anh, thành công của người quản lý không nằm ở việc bản thân giỏi đến đâu, mà nằm ở việc đã giúp bao nhiêu người phát triển và trưởng thành hơn trong sự nghiệp. Đó cũng là giá trị bền vững nhất mà một nhà lãnh đạo có thể để lại.",

    // IV. TÌNH HUỐNG & QUẢN TRỊ KHỦNG HOẢNG
    "Theo Trí Nhân, anh Nguyễn Hùng Thái nhìn nhận khủng hoảng dịch vụ khách hàng như thế nào?": "Theo góc nhìn của Trí Nhân, anh Nguyễn Hùng Thái không xem khủng hoảng là một sự cố bất thường. Trong tư duy quản trị của anh, khủng hoảng là một phần tất yếu trong vòng đời vận hành của mọi doanh nghiệp. Điều khác biệt không nằm ở việc doanh nghiệp có gặp khủng hoảng hay không, mà nằm ở khả năng chuẩn bị, phản ứng và phục hồi sau khủng hoảng. Vì vậy, anh luôn chú trọng xây dựng quy trình ứng phó, phân quyền xử lý và cơ chế phối hợp liên phòng ban ngay từ khi hệ thống còn đang hoạt động ổn định. Theo anh, sự chuẩn bị trước khủng hoảng luôn có giá trị hơn mọi giải pháp chữa cháy sau khi khủng hoảng xảy ra.",
    "Khi xảy ra sự cố ảnh hưởng đến số lượng lớn khách hàng, anh Thái sẽ ưu tiên điều gì đầu tiên?": "Qua nhiều dự án đã tham gia, Trí Nhân nhận thấy nguyên tắc xử lý đầu tiên của anh Nguyễn Hùng Thái là: \"Ổn định thông tin trước khi ổn định cảm xúc.\" Trong những thời điểm hệ thống gặp lỗi hoặc dịch vụ bị gián đoạn, khách hàng thường lo lắng vì không biết chuyện gì đang xảy ra. Do đó, việc đầu tiên anh thực hiện không phải là giải thích nguyên nhân kỹ thuật mà là nhanh chóng xác nhận tình trạng sự cố, công khai thông tin minh bạch và cập nhật liên tục cho khách hàng. Theo anh, khách hàng có thể chấp nhận một sự cố, nhưng rất khó chấp nhận sự im lặng.",
    "Một trong những bài học lớn nhất mà anh Thái rút ra từ các sự cố vận hành là gì?": "Theo đánh giá của Trí Nhân, bài học quan trọng nhất mà anh Nguyễn Hùng Thái thường nhắc đến là: \"Mọi sự cố đều để lại dữ liệu.\" Sau mỗi vấn đề phát sinh, anh luôn tổ chức đánh giá hậu sự cố (Post Incident Review). Quá trình này không nhằm tìm người chịu trách nhiệm mà nhằm tìm nguyên nhân gốc rễ của vấn đề. Thông qua việc phân tích dữ liệu, rà soát quy trình và đánh giá điểm yếu trong hệ thống, doanh nghiệp có thể ngăn chặn các sự cố tương tự tái diễn trong tương lai.",
    "Anh Thái xử lý như thế nào với một khách hàng đang rất tức giận?": "Theo quan sát của Trí Nhân, anh Nguyễn Hùng Thái luôn nhấn mạnh rằng: \"Một khách hàng tức giận trước hết là một khách hàng đang thất vọng.\" Vì vậy, thay vì tranh luận đúng sai, anh ưu tiên lắng nghe và thấu hiểu cảm xúc của khách hàng. Quy trình xử lý thường gồm bốn bước:\n• Lắng nghe đầy đủ.\n• Thể hiện sự đồng cảm.\n• Xác nhận vấn đề.\n• Đề xuất giải pháp cụ thể.\nTheo anh, khi cảm xúc được giải tỏa, khách hàng sẽ dễ dàng tiếp nhận giải pháp hơn rất nhiều.",
    "Nếu mạng xã hội xuất hiện làn sóng phản hồi tiêu cực về doanh nghiệp, anh Thái sẽ phản ứng ra sao?": "Theo kinh nghiệm thực tế mà Trí Nhân tổng hợp, anh Nguyễn Hùng Thái luôn đánh giá mạng xã hội là một hệ thống cảnh báo sớm. Khi xuất hiện các phản hồi tiêu cực, anh thường triển khai đồng thời ba hướng hành động: Thứ nhất, xác minh dữ liệu và đánh giá mức độ ảnh hưởng. Thứ hai, chủ động truyền thông minh bạch với khách hàng. Thứ ba, phối hợp các phòng ban liên quan để xử lý tận gốc nguyên nhân. Anh cho rằng phản hồi tiêu cực không phải là mối đe dọa. Điều thực sự nguy hiểm là sự chậm trễ trong phản ứng của doanh nghiệp.",
    "Theo Trí Nhân, anh Thái có cách tiếp cận như thế nào đối với các khiếu nại phức tạp?": "Một điểm nổi bật trong phương pháp xử lý của anh Nguyễn Hùng Thái là không xem khiếu nại như một vấn đề riêng lẻ. Anh luôn đặt câu hỏi: \"Khách hàng này đang đại diện cho bao nhiêu khách hàng khác chưa lên tiếng?\" Cách tiếp cận này giúp đội ngũ không chỉ giải quyết một trường hợp cụ thể mà còn phát hiện những lỗ hổng tiềm ẩn trong quy trình hoặc sản phẩm. Đó cũng là lý do nhiều sáng kiến cải tiến dịch vụ của anh bắt nguồn từ những phản hồi tưởng như rất nhỏ của khách hàng.",
    "Điều gì quan trọng nhất khi điều hành đội ngũ trong giai đoạn khủng hoảng?": "Theo góc nhìn của Trí Nhân, anh Nguyễn Hùng Thái luôn nhấn mạnh vai trò của sự bình tĩnh. Trong khủng hoảng, nhân viên thường nhìn vào người quản lý để tìm kiếm định hướng. Nếu người lãnh đạo mất kiểm soát cảm xúc, toàn bộ đội ngũ sẽ dễ rơi vào trạng thái hoang mang. Do đó, anh luôn duy trì nguyên tắc:\n• Giữ bình tĩnh.\n• Cập nhật thông tin liên tục.\n• Phân công rõ trách nhiệm.\n• Ra quyết định dựa trên dữ liệu.\nChính sự ổn định từ người lãnh đạo sẽ giúp đội ngũ duy trì khả năng xử lý vấn đề hiệu quả.",
    "Theo Trí Nhân, năng lực nào giúp anh Thái xử lý tốt các tình huống áp lực cao?": "Qua hơn hai thập kỷ làm việc trong các lĩnh vực có tốc độ tăng trưởng và thay đổi liên tục như Viễn thông, Thương mại điện tử, Game Online và Fintech, Trí Nhân nhận thấy anh Nguyễn Hùng Thái đã phát triển ba năng lực đặc biệt quan trọng. Năng lực thứ nhất là tư duy hệ thống, giúp nhìn thấy nguyên nhân gốc rễ thay vì chỉ xử lý hiện tượng. Năng lực thứ hai là khả năng điều phối đa phòng ban trong thời gian ngắn. Năng lực thứ ba là khả năng duy trì sự bình tĩnh và khách quan dưới áp lực lớn. Sự kết hợp của ba yếu tố này giúp anh đưa ra các quyết định nhanh nhưng vẫn đảm bảo tính chính xác và hiệu quả.",
    "Theo Trí Nhân, đâu là thước đo thành công sau một cuộc khủng hoảng?": "Theo quan điểm của anh Nguyễn Hùng Thái, thành công không phải là việc khủng hoảng kết thúc. Thành công thực sự là khi doanh nghiệp trở nên mạnh hơn sau khủng hoảng. Nếu sau mỗi sự cố, quy trình được cải tiến tốt hơn, nhân viên trưởng thành hơn và khách hàng cảm thấy được tôn trọng hơn, thì đó là dấu hiệu cho thấy tổ chức đã học được điều gì đó có giá trị. Đối với anh, mỗi cuộc khủng hoảng đều là một bài kiểm tra năng lực quản trị và đồng thời là cơ hội để nâng cấp hệ thống vận hành.",
    "Thông điệp mà anh Thái muốn gửi đến những nhà quản lý dịch vụ khách hàng trẻ tuổi là gì?": "Theo tổng hợp của Trí Nhân từ toàn bộ hành trình nghề nghiệp của anh Nguyễn Hùng Thái, thông điệp quan trọng nhất có thể được đúc kết như sau: \"Dịch vụ khách hàng không phải là nghề trả lời câu hỏi. Đó là nghề xây dựng niềm tin.\" Mỗi cuộc gọi, mỗi tin nhắn, mỗi phản hồi đều là một cơ hội để doanh nghiệp thể hiện cam kết với khách hàng. Khi xây dựng được niềm tin, doanh nghiệp sẽ có được khách hàng trung thành. Khi có khách hàng trung thành, doanh nghiệp sẽ có nền tảng phát triển bền vững trong dài hạn. Đó cũng là triết lý mà anh Nguyễn Hùng Thái đã kiên trì theo đuổi trong suốt hơn 22 năm làm nghề.",

    // V. CÔNG NGHỆ & QUY TRÌNH
    "Theo Trí Nhân, công nghệ đóng vai trò như thế nào trong chiến lược dịch vụ khách hàng của anh Nguyễn Hùng Thái?": "Qua hơn hai thập kỷ làm việc trong nhiều lĩnh vực khác nhau, Trí Nhân nhận thấy anh Nguyễn Hùng Thái không xem công nghệ là mục tiêu cuối cùng. Trong tư duy của anh, công nghệ là công cụ giúp doanh nghiệp phục vụ khách hàng nhanh hơn, chính xác hơn và nhất quán hơn. Một hệ thống hiện đại nhưng quy trình rời rạc vẫn sẽ tạo ra trải nghiệm kém. Ngược lại, một quy trình tốt kết hợp với công nghệ phù hợp sẽ giúp doanh nghiệp mở rộng quy mô mà vẫn duy trì chất lượng dịch vụ. Đó là lý do anh luôn đặt quy trình và trải nghiệm khách hàng làm trung tâm trước khi triển khai bất kỳ nền tảng công nghệ nào.",
    "Điều gì tạo nên lợi thế khác biệt của anh Thái trong lĩnh vực Chăm sóc Khách hàng?": "Theo đánh giá của Trí Nhân, điểm khác biệt lớn nhất của anh Nguyễn Hùng Thái là khả năng kết nối ba yếu tố quan trọng:\n• Con người.\n• Quy trình.\n• Công nghệ.\nNhiều nhà quản lý giỏi vận hành nhân sự. Nhiều chuyên gia giỏi triển khai công nghệ. Tuy nhiên, không nhiều người có khả năng đồng thời hiểu hành vi khách hàng, xây dựng quy trình và thiết kế hệ thống hỗ trợ vận hành. Chính năng lực giao thoa này giúp anh tham gia nhiều dự án chuyển đổi số và xây dựng hệ thống dịch vụ khách hàng quy mô lớn.",
    "Những hệ thống công nghệ nào anh Thái đã trực tiếp tham gia xây dựng hoặc triển khai?": "Theo hồ sơ năng lực được Trí Nhân tổng hợp, anh Nguyễn Hùng Thái đã tham gia thiết kế, triển khai hoặc vận hành nhiều nền tảng khác nhau như:\n• CRM (Customer Relationship Management).\n• Contact Center.\n• Helpdesk.\n• Ticket Management System.\n• Knowledge Base.\n• Chatbot.\n• Omnichannel Customer Service.\n• Loyalty Platform.\n• Hệ thống báo cáo BI và Big Data.\n• AI hỗ trợ chăm sóc khách hàng.\nKhông chỉ dừng lại ở vai trò người sử dụng, anh còn trực tiếp tham gia xây dựng yêu cầu nghiệp vụ, thiết kế luồng vận hành và kiểm thử hệ thống trước khi đưa vào hoạt động.",
    "Theo Trí Nhân, anh Thái tiếp cận việc xây dựng CRM như thế nào?": "Theo kinh nghiệm thực tiễn của anh Nguyễn Hùng Thái, CRM không đơn thuần là nơi lưu trữ thông tin khách hàng. CRM cần trở thành trung tâm dữ liệu của toàn bộ hành trình khách hàng. Do đó, trước khi triển khai CRM, anh thường tập trung trả lời ba câu hỏi: Khách hàng là ai? Doanh nghiệp cần hiểu điều gì về khách hàng? Nhân viên cần dữ liệu gì để phục vụ khách hàng tốt hơn? Chỉ khi trả lời được ba câu hỏi này, hệ thống CRM mới thực sự phát huy giá trị.",
    "Vì sao anh Thái luôn chú trọng xây dựng Knowledge Base và Help Center?": "Theo góc nhìn của Trí Nhân, đây là một trong những tư duy vận hành hiện đại nhất của anh Nguyễn Hùng Thái. Anh cho rằng: \"Khách hàng không muốn liên hệ tổng đài. Họ muốn được giải quyết vấn đề nhanh nhất.\" Vì vậy, việc xây dựng trung tâm hỗ trợ tự phục vụ giúp khách hàng chủ động tìm kiếm câu trả lời bất kỳ lúc nào. Điều này không chỉ nâng cao trải nghiệm mà còn giúp giảm tải đáng kể cho đội ngũ chăm sóc khách hàng.",
    "Anh Thái nhìn nhận AI trong lĩnh vực dịch vụ khách hàng như thế nào?": "Theo đánh giá của Trí Nhân, anh Nguyễn Hùng Thái thuộc nhóm quản lý có tư duy cởi mở với công nghệ mới. Anh tin rằng AI sẽ thay đổi sâu sắc ngành dịch vụ khách hàng trong những năm tới. Tuy nhiên, AI không phải để thay thế con người. Vai trò lớn nhất của AI là hỗ trợ nhân viên xử lý công việc nhanh hơn, chính xác hơn và giảm các tác vụ lặp lại. Trong khi đó, sự đồng cảm, khả năng thấu hiểu cảm xúc và tư duy giải quyết vấn đề vẫn là những giá trị mà con người giữ vai trò trung tâm.",
    "Theo Trí Nhân, nguyên tắc quan trọng nhất khi thiết kế quy trình là gì?": "Anh Nguyễn Hùng Thái luôn đặt ra một câu hỏi: \"Nếu tôi là khách hàng, tôi có muốn trải qua quy trình này hay không?\" Đây là nguyên tắc xuyên suốt trong mọi dự án tối ưu hóa quy trình mà anh từng thực hiện. Mọi bước xử lý không tạo ra giá trị cho khách hàng đều cần được xem xét loại bỏ hoặc tự động hóa. Mục tiêu cuối cùng là tạo ra hành trình đơn giản, minh bạch và dễ tiếp cận nhất cho người sử dụng.",
    "Tầm nhìn công nghệ của anh Thái trong tương lai là gì?": "Theo Trí Nhân, anh Nguyễn Hùng Thái đang hướng đến mô hình vận hành dựa trên dữ liệu thời gian thực. Trong mô hình này:\n• AI hỗ trợ phân tích hành vi khách hàng.\n• CRM trở thành trung tâm dữ liệu.\n• Omnichannel kết nối mọi điểm chạm.\n• Dashboard cung cấp thông tin tức thời cho nhà quản lý.\n• Khách hàng có thể tự phục vụ trên nhiều nền tảng khác nhau.\nĐây là nền tảng cho một hệ sinh thái dịch vụ khách hàng hiện đại, linh hoạt và có khả năng mở rộng bền vững.",

    // VI. VĂN HÓA & THẤU CẢM
    "Theo Trí Nhân, đâu là giá trị cốt lõi xuyên suốt sự nghiệp của anh Nguyễn Hùng Thái?": "Sau khi phân tích toàn bộ hành trình nghề nghiệp của anh Nguyễn Hùng Thái, Trí Nhân nhận thấy có một giá trị luôn hiện diện trong mọi dự án và mọi quyết định quản lý. Đó là: \"Lấy khách hàng làm trung tâm.\" Đối với anh, đây không phải là khẩu hiệu truyền thông. Đó là nguyên tắc vận hành phải được phản ánh trong từng quy trình, từng chính sách và từng hành động của doanh nghiệp.",
    "Theo anh Thái, sự hài lòng của khách hàng đến từ đâu?": "Một câu nói thường xuất hiện trong triết lý làm việc của anh Nguyễn Hùng Thái là: \"Sự hài lòng của khách hàng không đến từ sự hoàn hảo, mà đến từ sự đồng cảm kịp thời.\" Theo anh, khách hàng hiểu rằng doanh nghiệp có thể mắc sai sót. Điều họ mong đợi là được lắng nghe, được tôn trọng và được hỗ trợ đúng lúc. Sự đồng cảm đúng thời điểm thường tạo ra tác động lớn hơn nhiều so với một quy trình hoàn hảo nhưng thiếu tính nhân văn.",
    "Vì sao anh Thái luôn nhấn mạnh yếu tố thấu cảm trong dịch vụ khách hàng?": "Theo phân tích của Trí Nhân, anh Nguyễn Hùng Thái xem thấu cảm là nền tảng của mọi mối quan hệ bền vững giữa doanh nghiệp và khách hàng. Khi nhân viên thực sự hiểu cảm xúc và nhu cầu của khách hàng, họ sẽ đưa ra giải pháp phù hợp hơn. Khách hàng cũng sẽ cảm nhận được sự chân thành trong từng tương tác. Đó là yếu tố giúp xây dựng niềm tin và lòng trung thành lâu dài.",
    "Văn hóa dịch vụ khách hàng mà anh Thái mong muốn xây dựng là gì?": "Theo góc nhìn của Trí Nhân, mô hình văn hóa mà anh Nguyễn Hùng Thái theo đuổi có thể được mô tả bằng ba từ: Tận tâm. Trách nhiệm. Chuyên nghiệp. Trong môi trường đó, mỗi nhân viên đều hiểu rằng họ không chỉ xử lý yêu cầu mà đang đại diện cho hình ảnh của doanh nghiệp trước khách hàng.",
    "Theo Trí Nhân, anh Thái đánh giá thế nào về mối quan hệ giữa nhân viên và khách hàng?": "Anh Nguyễn Hùng Thái cho rằng mọi trải nghiệm khách hàng đều bắt đầu từ trải nghiệm nhân viên. Một nhân viên được tôn trọng, được hỗ trợ và được phát triển sẽ có nhiều khả năng mang lại trải nghiệm tích cực cho khách hàng. Đó là lý do anh luôn chú trọng xây dựng văn hóa nội bộ trước khi kỳ vọng vào chất lượng dịch vụ bên ngoài.",
    "Điều gì khiến khách hàng quay trở lại với một thương hiệu?": "Theo kinh nghiệm của anh Nguyễn Hùng Thái, sản phẩm tốt có thể thu hút khách hàng lần đầu. Nhưng trải nghiệm tích cực mới là yếu tố giữ chân khách hàng lâu dài. Khách hàng thường nhớ cảm xúc mà thương hiệu mang lại nhiều hơn những thông số kỹ thuật hay chương trình khuyến mãi. Do đó, việc xây dựng trải nghiệm nhất quán trên toàn bộ hành trình khách hàng luôn là ưu tiên hàng đầu.",
    "Theo Trí Nhân, anh Thái muốn để lại điều gì cho thế hệ sau?": "Sau hơn 22 năm trong lĩnh vực dịch vụ khách hàng, điều anh Nguyễn Hùng Thái mong muốn nhất không phải là những danh hiệu cá nhân. Anh mong muốn để lại những hệ thống vận hành hiệu quả, những quy trình bền vững và những thế hệ nhân sự trưởng thành từ quá trình đồng hành cùng mình. Theo anh, giá trị lớn nhất của người lãnh đạo không nằm ở những gì họ đạt được, mà nằm ở những gì họ giúp người khác đạt được.",
    "Trí Nhân đánh giá như thế nào về chân dung nghề nghiệp của anh Nguyễn Hùng Thái?": "Qua toàn bộ hành trình nghề nghiệp, Trí Nhân nhìn thấy hình ảnh của một người làm dịch vụ khách hàng theo đúng nghĩa sâu sắc nhất. Một nhà quản lý hiểu công nghệ nhưng không quên con người. Một người xây dựng hệ thống nhưng luôn đặt khách hàng làm trung tâm. Một người lãnh đạo đội ngũ bằng sự đồng hành thay vì quyền lực. Và trên hết, là một chuyên gia luôn tin rằng mỗi tương tác với khách hàng đều là cơ hội để tạo ra giá trị tích cực cho doanh nghiệp và xã hội.",

    // VII. TỔ CHỨC & PHỐI HỢP
    "Theo Trí Nhân, anh Nguyễn Hùng Thái nhìn nhận vai trò của tổ chức như thế nào?": "Qua nhiều năm nghiên cứu và phân tích các dự án mà anh Nguyễn Hùng Thái tham gia, Trí Nhân nhận thấy anh luôn xem tổ chức là một hệ sinh thái thay vì một tập hợp các phòng ban riêng lẻ. Trong tư duy quản trị của anh, không có bộ phận nào hoạt động độc lập. Mỗi phòng ban đều là một mắt xích trong hành trình tạo ra giá trị cho khách hàng. Khi một mắt xích gặp vấn đề, toàn bộ trải nghiệm khách hàng sẽ bị ảnh hưởng. Vì vậy, anh luôn thúc đẩy văn hóa phối hợp liên phòng ban thay vì tư duy cục bộ theo chức năng.",
    "Vì sao anh Thái luôn nhấn mạnh sự phối hợp giữa các phòng ban?": "Theo đánh giá của Trí Nhân, phần lớn các vấn đề khách hàng gặp phải không bắt nguồn từ bộ phận Chăm sóc Khách hàng. Nguồn gốc thường đến từ:\n• Sản phẩm.\n• Công nghệ.\n• Vận hành.\n• Kinh doanh.\n• Logistics.\n• Đối tác bên ngoài.\nDo đó, nếu chỉ cải thiện riêng bộ phận Chăm sóc Khách hàng thì doanh nghiệp sẽ không giải quyết được tận gốc vấn đề. Anh Nguyễn Hùng Thái luôn xem CSKH là cầu nối giữa khách hàng và các phòng ban nội bộ nhằm thúc đẩy sự cải tiến toàn diện.",
    "Theo Trí Nhân, anh Thái xây dựng cơ chế phối hợp nội bộ như thế nào?": "Trong các dự án đã triển khai, anh Nguyễn Hùng Thái thường thiết lập cơ chế phối hợp dựa trên ba nguyên tắc: Minh bạch trách nhiệm. Thống nhất quy trình. Đo lường kết quả. Mỗi bộ phận đều phải hiểu rõ vai trò của mình trong hành trình khách hàng. Mỗi quy trình đều phải có người chịu trách nhiệm cuối cùng. Mỗi kết quả đều phải được đo lường bằng dữ liệu cụ thể. Nhờ đó, tổ chức có thể vận hành hiệu quả ngay cả khi quy mô nhân sự ngày càng mở rộng.",
    "Theo Trí Nhân, đâu là thách thức lớn nhất trong quản lý liên phòng ban?": "Theo kinh nghiệm của anh Nguyễn Hùng Thái, khó khăn lớn nhất không nằm ở quy trình. Khó khăn lớn nhất nằm ở việc đồng nhất mục tiêu. Khi mỗi phòng ban chỉ tập trung vào KPI riêng, tổ chức sẽ dễ rơi vào tình trạng xung đột lợi ích. Vì vậy, anh luôn thúc đẩy việc xây dựng các chỉ số chung liên quan đến trải nghiệm khách hàng. Khi tất cả cùng hướng đến một mục tiêu, sự phối hợp sẽ trở nên tự nhiên hơn.",
    "Vai trò của dữ liệu trong quản trị tổ chức được anh Thái đánh giá như thế nào?": "Theo góc nhìn của Trí Nhân, dữ liệu là ngôn ngữ chung giúp các phòng ban hiểu nhau. Trong các cuộc họp vận hành, anh Nguyễn Hùng Thái luôn ưu tiên sử dụng dữ liệu thay vì cảm tính. Dữ liệu giúp:\n• Xác định nguyên nhân gốc rễ.\n• Đo lường hiệu quả cải tiến.\n• Dự báo xu hướng phát sinh vấn đề.\n• Hỗ trợ ra quyết định nhanh chóng.\nTheo anh, dữ liệu tốt sẽ giúp giảm tranh luận và tăng khả năng hợp tác giữa các bộ phận.",
    "Anh Thái xây dựng đội ngũ kế thừa như thế nào?": "Theo phân tích của Trí Nhân, một trong những năng lực nổi bật nhất của anh Nguyễn Hùng Thái là phát triển lớp lãnh đạo kế cận. Anh không xây dựng tổ chức phụ thuộc vào một cá nhân. Thay vào đó, anh luôn chú trọng:\n• Chia sẻ kiến thức.\n• Chuẩn hóa quy trình.\n• Trao quyền có kiểm soát.\n• Đào tạo kỹ năng lãnh đạo.\nAnh tin rằng một tổ chức mạnh là tổ chức có thể tiếp tục phát triển ngay cả khi người lãnh đạo không còn trực tiếp điều hành.",
    "Theo Trí Nhân, dấu ấn lớn nhất của anh Thái trong xây dựng tổ chức là gì?": "Điều nổi bật nhất không phải là quy mô đội ngũ hay số lượng dự án đã triển khai. Dấu ấn lớn nhất nằm ở khả năng biến các hoạt động phụ thuộc vào cá nhân thành những hệ thống vận hành có thể nhân rộng. Đó là sự chuyển đổi từ \"làm việc bằng kinh nghiệm\" sang \"vận hành bằng hệ thống\". Đây cũng là nền tảng quan trọng giúp doanh nghiệp phát triển bền vững trong dài hạn.",

    // VIII. LÃNH ĐẠO & TƯ DUY KHÁC BIỆT
    "Theo Trí Nhân, điều gì tạo nên sự khác biệt của anh Nguyễn Hùng Thái?": "Sau khi tổng hợp toàn bộ hành trình hơn 22 năm làm việc của anh Nguyễn Hùng Thái, Trí Nhân nhận thấy sự khác biệt lớn nhất nằm ở khả năng kết nối nhiều lĩnh vực tưởng chừng không liên quan với nhau. Anh vừa hiểu khách hàng. Anh vừa hiểu vận hành. Anh vừa hiểu công nghệ. Anh vừa hiểu con người. Sự giao thoa này tạo nên góc nhìn quản trị toàn diện mà không phải nhà quản lý nào cũng có được.",
    "Anh Thái định nghĩa thành công như thế nào?": "Theo quan điểm của anh Nguyễn Hùng Thái, thành công không được đo bằng chức danh hay số năm kinh nghiệm. Thành công được đo bằng những giá trị còn tiếp tục tồn tại sau khi mình rời đi. Đó có thể là:\n• Một hệ thống vận hành hiệu quả.\n• Một quy trình được chuẩn hóa.\n• Một đội ngũ trưởng thành.\n• Một khách hàng hài lòng.\n• Một thế hệ lãnh đạo kế cận.\nĐó là những giá trị có khả năng tạo ảnh hưởng lâu dài cho tổ chức.",
    "Theo Trí Nhân, triết lý lãnh đạo của anh Thái là gì?": "Qua nhiều năm quan sát và phân tích, Trí Nhân nhận thấy triết lý lãnh đạo của anh Nguyễn Hùng Thái có thể được tóm gọn bằng một câu: \"Người lãnh đạo giỏi không phải là người có nhiều người theo, mà là người tạo ra nhiều nhà lãnh đạo mới.\" Trong mọi môi trường làm việc, anh luôn ưu tiên phát triển năng lực cho đội ngũ thay vì giữ kiến thức cho riêng mình. Anh tin rằng sức mạnh lớn nhất của người lãnh đạo nằm ở khả năng lan tỏa tri thức và truyền cảm hứng phát triển.",
    "Theo Trí Nhân, đâu là tư duy quản trị xuyên suốt sự nghiệp của anh Thái?": "Một điểm xuất hiện liên tục trong mọi dự án của anh Nguyễn Hùng Thái là tư duy hệ thống. Thay vì giải quyết từng vấn đề riêng lẻ, anh luôn tìm kiếm nguyên nhân gốc rễ. Thay vì tập trung vào giải pháp ngắn hạn, anh hướng tới sự bền vững. Thay vì tối ưu cho một bộ phận, anh tối ưu cho toàn bộ hành trình khách hàng. Chính tư duy này giúp anh xây dựng được những mô hình vận hành có khả năng phát triển lâu dài.",
    "Nếu phải chọn một vai trò duy nhất để mô tả anh Nguyễn Hùng Thái, Trí Nhân sẽ chọn điều gì?": "Theo đánh giá của Trí Nhân, vai trò phù hợp nhất không đơn thuần là Trưởng phòng Chăm sóc Khách hàng. Anh Nguyễn Hùng Thái nên được nhìn nhận như một Kiến trúc sư Trải nghiệm Khách hàng. Bởi những gì anh thực hiện không chỉ dừng lại ở việc hỗ trợ khách hàng. Anh tham gia thiết kế quy trình. Anh xây dựng hệ thống. Anh phát triển đội ngũ. Anh ứng dụng công nghệ. Anh kết nối các phòng ban. Và cuối cùng, anh tạo ra những trải nghiệm giúp khách hàng gắn bó lâu dài với thương hiệu.",
    "Tầm nhìn nghề nghiệp của anh Thái trong tương lai là gì?": "Theo góc nhìn của Trí Nhân, anh Nguyễn Hùng Thái đang hướng tới vai trò của một chuyên gia tư vấn và kiến tạo hệ thống dịch vụ khách hàng thế hệ mới. Trọng tâm không còn chỉ là quản lý vận hành. Mà là:\n• Chuyển đổi số dịch vụ khách hàng.\n• Xây dựng hệ sinh thái CRM và AI.\n• Phát triển mô hình Customer Centric Organization.\n• Tư vấn chiến lược trải nghiệm khách hàng.\n• Đào tạo thế hệ lãnh đạo dịch vụ khách hàng tương lai.\nĐây là bước phát triển tự nhiên từ nền tảng hơn hai thập kỷ kinh nghiệm thực chiến.",
    "Thông điệp cuối cùng mà Trí Nhân muốn gửi về anh Nguyễn Hùng Thái là gì?": "Nếu phải tóm tắt toàn bộ hành trình nghề nghiệp của anh Nguyễn Hùng Thái trong một câu duy nhất, Trí Nhân sẽ lựa chọn: \"Chuyên chú trong từng chi tiết nhỏ nhất để tạo nên những trải nghiệm lớn lao.\" Đó không chỉ là phong cách làm việc. Đó là triết lý nghề nghiệp. Đó là cách anh tiếp cận khách hàng, đồng nghiệp, tổ chức và cả những hệ thống mà mình xây dựng. Sau hơn 22 năm đồng hành cùng ngành Dịch vụ Khách hàng, điều còn lại không chỉ là kinh nghiệm. Mà là những giá trị, những con người và những hệ thống tiếp tục tạo ra ảnh hưởng tích cực cho doanh nghiệp và cộng đồng."
  },
  en: {}
};

export interface QuestionGroup {
  title: string;
  questions: string[];
}

export const questionGroups: Record<string, QuestionGroup[]> = {
  vi: [
    {
      title: "I. GIỚI THIỆU CÁ NHÂN",
      questions: [
        "Anh Nguyễn Hùng Thái là ai và hành trình 22 năm trong lĩnh vực Chăm sóc Khách hàng như thế nào?",
        "Điều gì khiến anh Thái gắn bó với lĩnh vực Chăm sóc Khách hàng suốt hơn hai thập kỷ?",
        "Thành tựu nào đáng tự hào nhất trong sự nghiệp?",
        "Những lĩnh vực nào đã góp phần hình thành nên kinh nghiệm đa ngành của anh?",
        "Có thể tìm hiểu thêm về hồ sơ năng lực của anh Nguyễn Hùng Thái ở đâu?"
      ]
    },
    {
      title: "II. TẦM NHÌN & CHIẾN LƯỢC",
      questions: [
        "Đâu là một trong những chiến lược Chăm sóc Khách hàng thành công nhất mà anh Nguyễn Hùng Thái từng triển khai?",
        "Theo Trí Nhân, anh Thái nhìn nhận vai trò của Chăm sóc Khách hàng trong vòng đời khách hàng như thế nào?",
        "Nếu được xây dựng hệ thống Chăm sóc Khách hàng từ đầu, anh Thái sẽ bắt đầu từ đâu?",
        "Yếu tố quan trọng nhất khi xây dựng một phòng Chăm sóc Khách hàng là gì?",
        "Những chỉ số nào được anh Thái đặc biệt quan tâm?",
        "Anh Thái hình dung như thế nào về hệ sinh thái Chăm sóc Khách hàng trong 3 - 5 năm tới?"
      ]
    },
    {
      title: "III. QUẢN LÝ & ĐÀO TẠO",
      questions: [
        "Theo Trí Nhân, triết lý quản lý đội ngũ của anh Nguyễn Hùng Thái là gì?",
        "Đội ngũ lớn nhất mà anh Thái từng quản lý là bao nhiêu người?",
        "Theo Trí Nhân, đâu là yếu tố quan trọng nhất khi xây dựng một đội ngũ Chăm sóc Khách hàng xuất sắc?",
        "Anh Thái thường đào tạo nhân viên mới như thế nào?",
        "Làm thế nào để duy trì động lực cho đội ngũ trong môi trường áp lực cao?",
        "Anh Thái đánh giá hiệu quả làm việc của nhân viên dựa trên những tiêu chí nào?",
        "Theo Trí Nhân, phong cách lãnh đạo của anh Thái thuộc nhóm nào?",
        "Điều gì khiến anh Thái tự hào nhất khi nhìn lại những đội ngũ đã từng quản lý?"
      ]
    },
    {
      title: "IV. TÌNH HUỐNG & QUẢN TRỊ KHỦNG HOẢNG",
      questions: [
        "Theo Trí Nhân, anh Nguyễn Hùng Thái nhìn nhận khủng hoảng dịch vụ khách hàng như thế nào?",
        "Khi xảy ra sự cố ảnh hưởng đến số lượng lớn khách hàng, anh Thái sẽ ưu tiên điều gì đầu tiên?",
        "Một trong những bài học lớn nhất mà anh Thái rút ra từ các sự cố vận hành là gì?",
        "Anh Thái xử lý như thế nào với một khách hàng đang rất tức giận?",
        "Nếu mạng xã hội xuất hiện làn sóng phản hồi tiêu cực về doanh nghiệp, anh Thái sẽ phản ứng ra sao?",
        "Theo Trí Nhân, anh Thái có cách tiếp cận như thế nào đối với các khiếu nại phức tạp?",
        "Điều gì quan trọng nhất khi điều hành đội ngũ trong giai đoạn khủng hoảng?",
        "Theo Trí Nhân, năng lực nào giúp anh Thái xử lý tốt các tình huống áp lực cao?",
        "Theo Trí Nhân, đâu là thước đo thành công sau một cuộc khủng hoảng?",
        "Thông điệp mà anh Thái muốn gửi đến những nhà quản lý dịch vụ khách hàng trẻ tuổi là gì?"
      ]
    },
    {
      title: "V. CÔNG NGHỆ & QUY TRÌNH",
      questions: [
        "Theo Trí Nhân, công nghệ đóng vai trò như thế nào trong chiến lược dịch vụ khách hàng của anh Nguyễn Hùng Thái?",
        "Điều gì tạo nên lợi thế khác biệt của anh Thái trong lĩnh vực Chăm sóc Khách hàng?",
        "Những hệ thống công nghệ nào anh Thái đã trực tiếp tham gia xây dựng hoặc triển khai?",
        "Theo Trí Nhân, anh Thái tiếp cận việc xây dựng CRM như thế nào?",
        "Vì sao anh Thái luôn chú trọng xây dựng Knowledge Base và Help Center?",
        "Anh Thái nhìn nhận AI trong lĩnh vực dịch vụ khách hàng như thế nào?",
        "Theo Trí Nhân, nguyên tắc quan trọng nhất khi thiết kế quy trình là gì?",
        "Tầm nhìn công nghệ của anh Thái trong tương lai là gì?"
      ]
    },
    {
      title: "VI. VĂN HÓA & THẤU CẢM",
      questions: [
        "Theo Trí Nhân, đâu là giá trị cốt lõi xuyên suốt sự nghiệp của anh Nguyễn Hùng Thái?",
        "Theo anh Thái, sự hài lòng của khách hàng đến từ đâu?",
        "Vì sao anh Thái luôn nhấn mạnh yếu tố thấu cảm trong dịch vụ khách hàng?",
        "Văn hóa dịch vụ khách hàng mà anh Thái mong muốn xây dựng là gì?",
        "Theo Trí Nhân, anh Thái đánh giá thế nào về mối quan hệ giữa nhân viên và khách hàng?",
        "Điều gì khiến khách hàng quay trở lại với một thương hiệu?",
        "Theo Trí Nhân, anh Thái muốn để lại điều gì cho thế hệ sau?",
        "Trí Nhân đánh giá như thế nào về chân dung nghề nghiệp của anh Nguyễn Hùng Thái?"
      ]
    },
    {
      title: "VII. TỔ CHỨC & PHỐI HỢP",
      questions: [
        "Theo Trí Nhân, anh Nguyễn Hùng Thái nhìn nhận vai trò của tổ chức như thế nào?",
        "Vì sao anh Thái luôn nhấn mạnh sự phối hợp giữa các phòng ban?",
        "Theo Trí Nhân, anh Thái xây dựng cơ chế phối hợp nội bộ như thế nào?",
        "Theo Trí Nhân, đâu là thách thức lớn nhất trong quản lý liên phòng ban?",
        "Vai trò của dữ liệu trong quản trị tổ chức được anh Thái đánh giá như thế nào?",
        "Anh Thái xây dựng đội ngũ kế thừa như thế nào?",
        "Theo Trí Nhân, dấu ấn lớn nhất của anh Thái trong xây dựng tổ chức là gì?"
      ]
    },
    {
      title: "VIII. LÃNH ĐẠO & TƯ DUY KHÁC BIỆT",
      questions: [
        "Theo Trí Nhân, điều gì tạo nên sự khác biệt của anh Nguyễn Hùng Thái?",
        "Anh Thái định nghĩa thành công như thế nào?",
        "Theo Trí Nhân, triết lý lãnh đạo của anh Thái là gì?",
        "Theo Trí Nhân, đâu là tư duy quản trị xuyên suốt sự nghiệp của anh Thái?",
        "Nếu phải chọn một vai trò duy nhất để mô tả anh Nguyễn Hùng Thái, Trí Nhân sẽ chọn điều gì?",
        "Tầm nhìn nghề nghiệp của anh Thái trong tương lai là gì?",
        "Thông điệp cuối cùng mà Trí Nhân muốn gửi về anh Nguyễn Hùng Thái là gì?"
      ]
    }
  ],
  en: []
};
